/**
 * The 90-second walkthrough.
 *
 * Scenes are laid out on an absolute frame timeline from `SCENES` so a change
 * to one scene's length cannot silently shift the ones after it.
 */

import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { loadFont as loadBarlow } from "@remotion/google-fonts/Barlow";
import { loadFont as loadBarlowCondensed } from "@remotion/google-fonts/BarlowCondensed";
import { loadFont as loadPlexMono } from "@remotion/google-fonts/IBMPlexMono";

import {
  BoardScene,
  CloseScene,
  FactsScene,
  LedgerScene,
  RaceScene,
  TitleScene,
  UnknownScene,
} from "./scenes";
import { SCENES, theme } from "./theme";

loadBarlow();
loadBarlowCondensed();
loadPlexMono();

/**
 * Narration: one clip per scene, generated by narration/generate.py, starting
 * shortly after its scene opens so the visual lands first.
 */
const NARRATION = [
  { id: "title", from: 18 },
  { id: "board", from: 174 },
  { id: "facts", from: 558 },
  { id: "ledger", from: 1008 },
  { id: "unknown", from: 1518 },
  { id: "race", from: 1968 },
  { id: "close", from: 2508 },
] as const;

const TIMELINE = [
  { key: "title", scene: <TitleScene /> },
  { key: "board", scene: <BoardScene /> },
  { key: "facts", scene: <FactsScene /> },
  { key: "ledger", scene: <LedgerScene /> },
  { key: "unknown", scene: <UnknownScene /> },
  { key: "race", scene: <RaceScene /> },
  { key: "close", scene: <CloseScene /> },
] as const;

export function Walkthrough() {
  return (
    <AbsoluteFill style={{ background: theme.ground }}>
      {TIMELINE.map(({ key, scene }) => (
        <Sequence key={key} name={key} {...SCENES[key]}>
          {scene}
        </Sequence>
      ))}

      {NARRATION.map(({ id, from }) => (
        <Sequence key={`vo-${id}`} name={`vo-${id}`} from={from}>
          <Audio src={staticFile(`vo/${id}.wav`)} />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
}
